apiVersion: v1
kind: Pod
metadata:
    name: kaniko-example-2
spec:
    containers:
    - name: kaniko
      readinessProbe:
        exec:
          command:
          - cat
          - /Dockerfile
        initialDelaySeconds: 1
        periodSeconds: 5
      image: gcr.io/kaniko-project/executor:latest
      args: ["--dockerfile=Dockerfile",
              "--context=git://github.com/youruser/repo",
              "--destination=index.docker.io/youruser/repo:example2"] # replace with your dockerhub account eg: index.docker.io/youruser/repo
    restartPolicy: Never