apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build
spec:
  inputs:
    resources:
    - name: github-repo
      type: git
    - name: dockerhub-image
      type: image
    params:
    # - name: imageUrl
    #   description: something
    #   default: index.docker.io/cariza/tekton-prac:tekton-pipeline
    - name: pathToDockerFile
      description: The path to the dockerfile to build
      default: github-repo/Dockerfile
    - name: pathToContext
      description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: dir://github-repo
    # outputs:
    #   resources:
    #     - name: build-image
  steps:
  - name: build
    image: gcr.io/kaniko-project/executor:v0.9.0
    env:
    - name: "DOCKER_CONFIG"
      value: "/builder/home/.docker/" 
    command:
    - /kaniko/executor
    args:
    - --dockerfile=$(inputs.params.pathToDockerFile)
    - --destination=$(inputs.resources.dockerhub-image.url)
    - --context=$(inputs.params.pathToContext)
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: kaniko-secret
      mountPath: /builder/home
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run
spec:
  inputs:
    resources:
    - name: dockerhub-image
      type: image
    params:
    - name: imageUrl
      description: something
      default: index.docker.io/cariza/tekton-prac:tekton-pipeline
  steps:
  - name: run
    # image: $(inputs.params.imageUrl)
    image: "$(inputs.params.imageUrl)"
    # command: 
    # - echo
    # args:
    # - "hello $(inputs.resources.dockerhub-image.url)"
