apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: read-task
spec:
  inputs:
    resources:
      - name: github-repo
        type: git
  steps:
    - name: catreadme
      image: ubuntu
      command:
        - cat
      args:
        - "github-repo/README.md"
        