# ---
# apiVersion: tekton.dev/v1alpha1
# kind: PipelineResource
# metadata:
#   name: skaffold-image-leeroy-app
# spec:
#   type: image
#   params:
#   - name: url
#     value: gcr.io/christiewilson-catfactory/leeroy-app
# ---
# This demo modifies the cluster (deploys to it) you must use a service
# account with permission to admin the cluster (or make your default user an admin
# of the `default` namespace with default-cluster-admin.

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   generateName: default-cluster-admin-
# subjects:
#   - kind: ServiceAccount
#     name: default
#     namespace: default
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: tekton.dev/v1alpha1
# kind: PipelineResource
# metadata:
#   name: skaffold-image-leeroy-web-pipelinerun
# spec:
#   type: image
#   params:
#   - name: url
#     value: gcr.io/christiewilson-catfactory/leeroy-web
# ---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: github-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/CariZa/ulmaceae